### ISSUE TITLE
Need ability to install a software repository

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#120]
This is VLI-specific right now, but seems like a useful feature in general.

`SFS` (Software Foundation Services) software is distributed as a repository. Currently, we can install RPMs (which is great for UCS, since their drivers are distributed as .rpm files with no dependencies). But `SFS` is distributed as a repository.

My thought here is that SFS would be in a directory on the configuration LUN (perhaps `/sfsrepo`), and I can point to that from the YAML to process it as a repository.

Here's the rough instructions I have for installing `SFS` today:

- Download the foundation-2.19-cd1-media-sles12sp3-x86_64.iso image file to the server.

- Add System Foundation Software as a new software repository. The following example shows how to configure ISO as a new software repository:

```
# zypper ar -c -t yast2 "iso:/?iso=/var/foundation-2.19.iso" "SFS-2.19"  ß Change the path
Adding repository 'SFS-2.19' ......................................[done]
Repository 'SFS-2.19' successfully added
Enabled: Yes
Autorefresh: No
GPG check: Yes
URI: iso:///?iso=/var/foundation-2.19.iso
```

- Refresh the software repository metadata.

```
#zypper refresh
```

- Install the System Foundation Software pattern

```
#zypper install -t pattern System-Foundation-Software
<Follow any on-screen instructions to complete the installation.>
```

- Reboot the system to complete the installation

It's annoying that SFS requires a reboot to get going - presumably you can combine this one, if needed (make it optional based on YAML), with the "non-post" (quick) reboot for crash dumps.

Doable? For YAML, perhaps something like:

```
packages:
  repository_name: azure_packages
  directory:
    - "rpms/" 
  repository:
    - 
    Directory: "sfsrepo/"
    Pattern: System-Foundation-Software
    -
    Directory: "anotherrepo/"
    Pattern: "Another-Pattern"
    -
  reboot: yes
```

If `reboot` wasn't specified, or if it was specified with something other than `yes` (or `true`?), then the system wouldn't be rebooted just for the repository installation.

Something like this, anyway.

Thoughts or suggestions?

**Comment by jeffaco** [comment]
Oh, note the very first step:

```
zypper ar -c -t yast2 "iso:/?iso=/var/foundation-2.19.iso" "SFS-2.19"
```

That isn't accounted for in the YAML. I could either extract the ISO myself prior to putting it on configuration LUN (and then you'd need to "add" that repo yourself), or we'd need to do something else where I have the full name of the ISO file.

**Comment by schaefi** [comment]
The implementation to install custom rpm's also creates a repo and registers that to zypper. So it's no problem to extend that feature to register an existing iso as another repo. 

> My thought here is that SFS would be in a directory on the configuration LUN (perhaps /sfsrepo), and I > can point to that from the YAML to process it as a repository. 

ok makes sense to me. Please put the repo file ```foundation-2.19.iso``` as such to the LUN. No extraction or changes to the file please, just put it there as you get it from FSF. 

I will extend the schema to allow the following setup:

```yaml
packages:
  -
    repository_name: A
    directory:
      - dir_A

  -
    repository_name: B
    repo_uri: zypper_repo_uri
    install:
       - package-or-pattern-name
       - ...
```

The existing package installer installs everything from the specified directories. I will keep this behavior. However if a section specifies install: items those will be taken into account. In the above example this will lead to two repos A and B registered to zypper and an install call ```zypper in "all_packs_found_in_dir_A" package-or-pattern-name```

You will also have the ability to specify install: for repository definitions based on directories. If you don't the behavior as it is now applies, which means install all packages found in that directories
