### ISSUE TITLE
Require password change on first login

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#121]
We would like the ability to (optionally) require a password change on first successful login. Perhaps something like this:

```
credentials:
 -
  username: "h31adm"
  id: 1031
  group:
    name: sapsys
    id: 1010
  shadow_hash: "<some-hash>"
  require_password_change: yes
  ssh-key: "<some-public-key>"
  ssh-private-key: "ssh/id_dsa_netapp"
 -
  username: "root"
  shadow_hash: "<some-hash>"
  ssh-key: "<some-public-key>"
```

The idea: `require_password_change` being `true` (or `yes`, perhaps) would set things up where, on first successful login, the user was required to change the password.
