### ISSUE TITLE
LI: Installation of UCS drivers require O/S reboot ...

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#162]
It turns out that when UCS drivers are installed (via the RPM package installation facility), the modules are not re-loaded until reboot. This is because we're booted off of SAN, so it's not possible to reload the driver without rebooting the O/S (since you'd lose access to the system disk).

We already have a means to do a kexec, if needed, for crash dump. Could this facility be used to reload to insure the proper UCS drivers are installed?

Currently, to install RPM package, we have YAML verbiage like:

```
packages:
  raw:
    name: azure_packages
    directory:
      - "rpms/" 
```

My thought was, since this was a list, we could put UCS RPMs in a separate directly. That way, we could have something like:

```
packages:
  raw:
    name: azure_packages
    directory:
      - "rpms/" 
    --
    name: ucs_drivers
    directory:
      - "rpms_ucs/"
    require_reboot: true
```

The `require_reboot` flag would indicate that kexec (assuming that will reload all modules) process in the cleanup service should be run if any RPMs are installed from that directory.

Let me know if you have questions or concerns about this, thanks.
